### ISSUE TITLE
Update tdworkflow Dependency to Version 0.8.2 in digdaglog2sql

### ISSUE THREAD

**Issue by mkohei** [chezou/digdaglog2sql#6]
**Problem Description:**
When installing `digdaglog2sql`, it becomes apparent that the project relies on an outdated version of `tdworkflow`. For projects that utilize both `digdaglog2sql` and `tdworkflow`, the older version of `tdworkflow` poses challenges and limits usability.

**Steps to Reproduce:**
1. Install `digdaglog2sql` following the standard installation procedures.

**Expected Behavior:**
The `digdaglog2sql` project's dependencies should include `tdworkflow` version 0.8.2. This update is expected to enhance compatibility and functionality for users relying on the latest features and improvements of `tdworkflow`.

**Current Behavior:**
The project currently uses an older version of `tdworkflow`, which restricts the use of the latest features and improvements available in version 0.8.2.

**Attempted Solutions:**
- No specific solutions have been attempted yet, as the issue primarily requires an update in the project dependencies.

I kindly request that the dependency on `tdworkflow` within the `digdaglog2sql` project be updated to the latest version, 0.8.2, to ensure compatibility and to make the most of the recent advancements in `tdworkflow`.

Thank you for considering this request.

**Comment by chezou** [comment]
@mkohei Thank you for raising it. There is no objection to bump tdworkflow.

However, I'm busy for a while. If it's urgent, it'd be great to send a PR.

Thanks

**Comment by chezou** [comment]
Released v0.1.0 https://github.com/chezou/digdaglog2sql/releases/tag/v0.1.0
Available on PyPI as well https://pypi.org/project/digdaglog2sql/
